name: CI

on:
  push:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: uv sync

      - name: Install ruff and mypy
        run: uv pip install ruff mypy pytest

      - name: Ruff format
        run: python3 -m ruff format . --check

      - name: Ruff linter
        run: python3 -m ruff check . --fix

      - name: Mypy
        run: python3 -m mypy .

      - name: Unit tests
        run: python3 -m pytest ./core/tests/unit

      - name: Integration tests
        run: python3 -m pytest ./core/tests/integration

      - name: BDD tests
        run: python3 -m pytest ./core/tests/behaviour